DROP TABLE IF EXISTS BdVentasSucursalCenter.dbo.INVENTARIOS_DECLARACION_CC;
DROP TABLE IF EXISTS BdVentasSucursalCenter.dbo.CABECERA_PEDIDO_CC;
DROP TABLE IF EXISTS BdVentasSucursalCenter.dbo.INVENTARIO_CC;
DROP TABLE IF EXISTS BdVentasSucursalCenter.dbo.INVENTARIO_ESTADO_CC;
DROP TABLE IF EXISTS BdVentasSucursalCenter.dbo.PEDIDO_EXTRAORDINARIO_CC;


CREATE TABLE BdVentasSucursalCenter.dbo.INVENTARIOS_DECLARACION_CC (
	ID_INVENTARIOS_DECLARACION int IDENTITY(1,1) NOT NULL,
	ID_SUBCATEGORIA_2 int NOT NULL,
	NOMBRE_PRODUCTO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CANTIDAD int NOT NULL,
	FECHA_CONTEO date NULL,
	HORA_CONTEO time(0) NULL,
	ID_USUARIO int NOT NULL,
	FECHA_MODIFICACION date NULL,
	HORA_MODIFICACION time(0) NULL,
	USUARIO_MODIFICACION int NULL,
	ESTADO_CONTEO int DEFAULT 9 NULL,
	CANTIDAD_SOLICITADA int DEFAULT 0 NULL,
	ESTADO_SOLICITUD int DEFAULT 0 NULL,
	FECHA_SOLICITUD date NULL,
	HORA_SOLICITUD time(0) NULL,
	USUARIO_SOLICITUD int NULL,
	ADECUACION numeric(38,2) NULL,
	OBSERVACION varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CANTIDAD_ENVIADA int DEFAULT 0 NULL,
	TURNO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CANTIDAD_ACEPTADA int NULL,
	CANTIDAD_ADECUADA int NULL,
	OBSERVACION2 varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CANTIDAD_ENTREGADA int NULL,
	CANTIDAD_DEVUELTA int NULL,
	OBSERVACION3 varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRECARGADO bit DEFAULT 1 NULL,
	MINIMO int DEFAULT 0 NULL,
	DIAS_VENCE int NULL
);

CREATE TABLE BdVentasSucursalCenter.dbo.CABECERA_PEDIDO_CC (
	ID_CABECERA int IDENTITY(1,1) NOT NULL,
	ESTADO int NULL,
	FECHA varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERFIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHA_SOLICITUD datetime NULL,
	FECHA_PREPARACION datetime NULL,
	FECHA_RECEPCION datetime NULL,
	FECHA_ENTREGA datetime NULL,
	USUARIO_CONTEO int NULL,
	USUARIO_SOLICITUD int NULL,
	USUARIO_PREPARACION int NULL
);

CREATE TABLE BdVentasSucursalCenter.dbo.INVENTARIO_CC (
	ID_INVENTARIO int IDENTITY(1,1) NOT NULL,
	ID_SUB_CATEGORIA_2 int NULL,
	FECHA_PRODUCCION date NULL,
	FECHA_VENCIMIENTO date NULL,
	ID_ESTADO int NULL,
	ID_VENTA_DETALLE int NULL,
	ID_UBICACION int NULL,
	CONSTRAINT PK_INVENTARIO PRIMARY KEY (ID_INVENTARIO)
);

CREATE TABLE BdVentasSucursalCenter.dbo.INVENTARIO_ESTADO_CC (
	ID_INVENTARIO_ESTADO int IDENTITY(1,1) NOT NULL,
	DESCRIPCION nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_INVENTARIO_ESTADO PRIMARY KEY (ID_INVENTARIO_ESTADO)
);

CREATE TABLE BdVentasSucursalCenter.dbo.PEDIDO_EXTRAORDINARIO_CC (
	ID_PEDIDO_EXTRAORDINARIO int IDENTITY(1,1) NOT NULL,
	CATEGORIA_1 int NULL,
	CATEGORIA_2 int NULL,
	PRODUCTO_MADRE int NULL,
	MODIFICADO bit NULL,
	DETALLE text COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ESTADO int NULL,
	USUARIO int NULL,
	FECHA_ENTREGA_PEDIDO datetime NULL,
	FECHA_REGISTRO datetime NULL,
	CONSTRAINT PEDIDO_EXTRAORDINARIO_AE_PK PRIMARY KEY (ID_PEDIDO_EXTRAORDINARIO)
);

