
CREATE PROCEDURE dbo.CC_PRIMERA_DECLARACION   @INVENTARIO VARCHAR(MAX), @FECHA DATE, @HORA TIME, @USUARIO INT
AS 

DECLARE @TAMANIO INT, @INICIO INT, @ID_SUB_CATEGORIA_2 INT, @SUB_CATEGORIA_2 VARCHAR(MAX), @TURNO VARCHAR(MAX), @ADECUACION INT, @VENCE INT


SET @INICIO = 0
SET @TAMANIO = (SELECT COUNT(*) FROM OPENJSON(@INVENTARIO,'$.ELEMENTOS'))

INSERT INTO CABECERA_PEDIDO_CC (ESTADO, FECHA) VALUES(9, @FECHA)


WHILE @INICIO < @TAMANIO
	 BEGIN
		 
		SET @ID_SUB_CATEGORIA_2 = JSON_VALUE(@INVENTARIO, CONCAT('$.ELEMENTOS[', @INICIO, '].ID_SUB_CATEGORIA_2'))
		SET @SUB_CATEGORIA_2 = JSON_VALUE(@INVENTARIO, CONCAT('$.ELEMENTOS[', @INICIO, '].SUB_CATEGORIA_2'))
		SET @TURNO = JSON_VALUE(@INVENTARIO, CONCAT('$.ELEMENTOS[', @INICIO, '].TURNO'))
		SET @ADECUACION = JSON_VALUE(@INVENTARIO, CONCAT('$.ELEMENTOS[', @INICIO, '].ADECUACION'))
		SET @VENCE = JSON_VALUE(@INVENTARIO, CONCAT('$.ELEMENTOS[', @INICIO, '].DURACION'))
	 	
		INSERT INTO INVENTARIOS_DECLARACION_CC (ID_SUBCATEGORIA_2, NOMBRE_PRODUCTO, CANTIDAD, FECHA_CONTEO, HORA_CONTEO, ID_USUARIO, TURNO, ADECUACION, DIAS_VENCE)
		VALUES (@ID_SUB_CATEGORIA_2, @SUB_CATEGORIA_2, 0, @FECHA, @HORA, @USUARIO, @TURNO, @ADECUACION, @VENCE )
		SET @INICIO = @INICIO +1 
	 END

GO;

CREATE PROC CC_SET_INVENTARIO
@id_sub_categoria_2 int,
@fecha_produccion date,
@dias_vencimiento int,
@id_estado int,
@cantidad int,
@inicio int 
AS
while (@inicio<=@cantidad)
begin
	insert into INVENTARIO_CC(ID_SUB_CATEGORIA_2, FECHA_PRODUCCION, FECHA_VENCIMIENTO, ID_ESTADO) 
       values(@id_sub_categoria_2,@fecha_produccion, (SELECT DATEADD(DD, @dias_vencimiento, CONVERT(date, GETDATE()))), @id_estado)
	set @inicio +=1
end

GO;

CREATE PROCEDURE dbo.CC_SET_ITEM_DECLARACION @CANTIDAD INT, @FECHA DATE, @HORA TIME, @USUARIO INT, @PRODUCTO INT
AS 
UPDATE 
	INVENTARIOS_DECLARACION_CC 
SET 
	CANTIDAD = @CANTIDAD, 
	FECHA_MODIFICACION = @FECHA,
	HORA_MODIFICACION = @HORA,
	USUARIO_MODIFICACION = @USUARIO,
	CANTIDAD_SOLICITADA = 0
	
WHERE 
	FECHA_CONTEO = @FECHA AND ID_SUBCATEGORIA_2 = @PRODUCTO

GO;

CREATE PROCEDURE dbo.CC_SET_ITEM_ENTREGA @ENTREGADA INT, @REGRESADA INT , @FECHA DATE, @OBSERVACION VARCHAR(200), @PRODUCTO INT
AS 
UPDATE 
	INVENTARIOS_DECLARACION_CC 
SET 
	CANTIDAD_ENTREGADA  = @ENTREGADA,
	CANTIDAD_DEVUELTA = @REGRESADA,
	OBSERVACION3  = @OBSERVACION
WHERE 
	FECHA_CONTEO = @FECHA AND ID_SUBCATEGORIA_2 = @PRODUCTO

GO;

CREATE PROCEDURE dbo.CC_SET_ITEM_PREPARACION @CANTIDAD INT, @FECHA DATE, @OBSERVACION VARCHAR(200), @PRODUCTO INT, @ENVIO VARCHAR(MAX)
AS 
UPDATE 
	INVENTARIOS_DECLARACION_CC 
SET 
	CANTIDAD_ENVIADA  = @CANTIDAD, 
	CANTIDAD_ACEPTADA = @CANTIDAD,
	CANTIDAD_ENTREGADA = @CANTIDAD,
	OBSERVACION  = @OBSERVACION,
	TURNO = @ENVIO
WHERE 
	FECHA_CONTEO = @FECHA AND ID_SUBCATEGORIA_2 = @PRODUCTO

GO;

CREATE PROCEDURE dbo.CC_SET_ITEM_RECEPCION @CANTIDAD INT, @FECHA DATE, @OBSERVACION VARCHAR(200), @PRODUCTO INT
AS 
UPDATE 
	INVENTARIOS_DECLARACION_CC 
SET 
	CANTIDAD_ACEPTADA = @CANTIDAD,
	CANTIDAD_ENTREGADA = @CANTIDAD,
	CANTIDAD_DEVUELTA = (SELECT (CANTIDAD_ENVIADA-CANTIDAD_ACEPTADA) FROM INVENTARIOS_DECLARACION_CC WHERE 
	FECHA_CONTEO = @FECHA AND ID_SUBCATEGORIA_2 = @PRODUCTO),
	OBSERVACION  = @OBSERVACION
WHERE 
	FECHA_CONTEO = @FECHA AND ID_SUBCATEGORIA_2 = @PRODUCTO
GO;

CREATE PROCEDURE dbo.CC_SET_ITEM_SOLICITUD @CANTIDAD INT, @FECHA_CONTEO DATE, @FECHA DATE ,@HORA TIME, @USUARIO INT, @PRODUCTO INT, @PRECARGADO INT, @MINIMO INT
AS 
UPDATE 
	INVENTARIOS_DECLARACION_CC 
SET 
	CANTIDAD_SOLICITADA  = @CANTIDAD, 
	FECHA_SOLICITUD  = @FECHA,
	HORA_SOLICITUD = @HORA,
	USUARIO_SOLICITUD  = @USUARIO,
	CANTIDAD_ENVIADA = @CANTIDAD,
	CANTIDAD_ACEPTADA = @CANTIDAD,
	CANTIDAD_ENTREGADA = @CANTIDAD,
	PRECARGADO = @PRECARGADO,
	MINIMO = @MINIMO
WHERE 
	FECHA_CONTEO = @FECHA_CONTEO AND ID_SUBCATEGORIA_2 = @PRODUCTO